keys:
  - &users
    - &clover age1znwvqazshlpucwszxwt9ggrsgm02ntdtrys7700mcqufyuy62ansmr9yjv
  - &hosts
    - &auberon age1va0nsla36lc2twze2sejw5mepdc8arvfn56xmnrktxu7vyuaqyasllyama
    - &belisarius age1nm00s293arsxef7jufh6mv908mtz5873c62nqxvg3mz83vc95v8q7t69n6
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *clover
          - *auberon
          - *belisarius
