:PROPERTIES:
:header-args+: :results silent :exports code :eval never-export
:header-args:emacs-lisp+: :tangle init.el :results silent :exports code :eval never-export :comments org :padline no
:END:
#+TITLE: Clover's Emacs configuration
#+STARTUP: folded showall hideblocks

* Reference docs and packages
[[https://github.com/jamescherti/minimal-emacs.d/blob/main/early-init.el][Minimal emacs]]
[[https://github.com/spl3g/nixfiles/blob/db248781f3df30afe2aa9abe909f444fb587faf3/home-manager/homeModules/emacs/early-init.el#L125][Init helpers based on minimal emacs]]
[[https://github.com/jamescherti/inhibit-mouse.el][Inhibit mouse]]
[[https://github.com/jamescherti/stripspace.el][Whitespace cleanup alternative package]]

* Items to complete in this configuration.
Stored here until I get around to migrating into org-agenda when that
is setup.

- Org agenda / Denote
  https://github.com/ryuslash/git-auto-commit-mode
  Create single repo for both.
  Use directory locals for git auto commit.
  Need to figure out a way to pull.
  https://www.labri.fr/perso/nrougier/GTD/index.html
  Want to be able to add notes / update state of todo items. These should be
  captured nicely into drawers/timestamped sections.
- Embark act
- Build/Compile (pre-commit make)
- Aidermacs voice
- Copilot.
  As I don't like the overlay interupting, here's a
  suggestion on converting it to a manual completion
  system.
  https://www.reddit.com/r/emacs/comments/1hghlyh/struggling_with_aibased_capfs/
  https://robert.kra.hn/posts/2023-02-22-copilot-emacs-setup/
- Minor mode management (easy enable/disable). Have previously done
  this using a transient, but not sure if this is the approach I want
  to take.
- re-builder default to rx

* Headers
#+begin_src emacs-lisp :comments no :tangle early-init.el
  ;;; Package --- early init file  -*- lexical-binding: t; no-byte-compile: t -*-

  ;;; Commentary:

  ;;; Code:
#+end_src

#+begin_src emacs-lisp
  ;;; Package --- init file  -*- lexical-binding: t; no-byte-compile: t -*-

  ;;; Commentary:

  ;;; Code:
#+end_src

#+begin_src emacs-lisp :tangle cnit-functions.el
  ;;; Package --- cnit functions file  -*- lexical-binding: t; no-byte-compile: t -*-

  ;;; Commentary:

  ;;; Code:
#+end_src

* Early Init
:PROPERTIES:
:header-args:emacs-lisp+: :tangle early-init.el
:END:

Startup time recording and reporting. As Emacs records the variables
can be called at any time, but for now is configured as an after
startup hook to report automatically.
#+begin_src emacs-lisp
  (defun display-startup-time ()
    "Display a message with the time it took to load Emacs."
    (message "Emacs loaded in %s."
             (format "%.2f seconds"
                     (float-time
                      (time-subtract
                       after-init-time before-init-time)))))
#+end_src

* Basic Emacs Settings
Load local packages autoloads
#+begin_src emacs-lisp
  (load "local-packages-autoloads")
#+end_src

Buffer display rules to organise new buffers opening where I want them
to.
#+begin_src emacs-lisp :tangle no
  (defun cnit-fit-window-to-buffer-with-max (window)
    (let ((fit-window-to-buffer-horizontally t))
      (fit-window-to-buffer
       window (floor (frame-height) 3) 0 (floor (frame-width) 3) 0)))

  (defconst cnit-regex-buffers-occur (rx "*Occur*"))
  (defconst cnit-regex-buffers-helpful (rx "*helpful" (1+ nonl) "*"))
  (defconst cnit-regex-buffers-info (rx "*info*"))

  (bind-key "C-`" #'popper-toggle)
  (bind-key "M-`" #'popper-cycle)
  (bind-key "C-M-`" #'popper-toggle-type)
  (with-eval-after-load 'popper
    (with-eval-after-load 'project
      (setopt
       popper-group-function #'popper-group-by-project))
    (setopt
     popper-display-control nil
     popper-mode-line nil
     popper-reference-buffers
     `(,cnit-regex-buffers-occur
       occur-mode ,cnit-regex-buffers-helpful helpful-mode))
    (popper-echo-mode 1))

  (setopt display-buffer-alist nil)

  (add-to-list
   'display-buffer-alist
   `((or . (,cnit-regex-buffers-occur (derived-mode-p 'occur-mode)))
     (display-buffer-in-side-window)
     (window-height . cnit-fit-window-to-buffer-with-max)
     (side . bottom)
     (dedicated . t)
     (body-function . select-window)
     (window-parameters (no-delete-other-windows . t))))

  (add-to-list
   'display-buffer-alist
   `((or .
         (,cnit-regex-buffers-helpful
          (derived-mode-p 'helpful-mode)
          ,cnit-regex-buffers-info
          (derived-mode-p 'Info-mode)))
     (display-buffer-in-side-window)
     (window-width . cnit-fit-window-to-buffer-with-max)
     (side . right)
     (dedicated . t)
     (body-function . select-window)
     (window-parameters (no-delete-other-windows . t))))

  ;; Magit buffers will prefer to reuse an existing window displaying
  ;; magit. Will use the current window if magit not showing anywhere.
  (with-eval-after-load 'magit
    (setopt magit-display-buffer-function #'display-buffer))
  (add-to-list
   'display-buffer-alist
   `((derived-mode . magit-mode)
     (display-buffer-reuse-mode-window display-buffer-same-window)
     (inhibit-same-window . nil)))
#+end_src

* cnit Functions
:PROPERTIES:
:header-args:emacs-lisp+: :tangle cnit-functions.el
:END:

This section is for defining custom funcions used throughout init and
my usage of Emacs. Each function should include requires for any
libraries it depends on. This ensures that the libraries are loaded,
but not until they are required.

Checking if the system is using dark or light mode.
#+begin_src emacs-lisp
  (defun cnit-system-colour-scheme ()
    "Return 'dark or 'light based on the system color scheme."
    (if (and (boundp 'cnit-gdbus-executable) cnit-gdbus-executable)
        (let*
            ((destination "org.freedesktop.portal.Desktop")
             (object-path "/org/freedesktop/portal/desktop")
             (method "org.freedesktop.portal.Settings.Read")
             (schema "org.freedesktop.appearance")
             (key "color-scheme")
             (command
              (format
               "%s call --session --dest %s --object-path %s --method %s %s %s"
               cnit-gdbus-executable
               destination
               object-path
               method
               schema
               key))
             (output (string-trim (shell-command-to-string command))))
          (if (string-match "(<<uint32 1>>,)" output)
              'dark
            'light))
      'light)) ; Default to light if gdbus is not available.

  (defmacro cnit-with-system-colour-scheme (dark-body light-body)
    "Execute DARK-BODY or LIGHT-BODY based on the system color scheme."
    `(let ((scheme (cnit-system-colour-scheme)))
       (cond
        ((eq scheme 'light)
         ,light-body)
        ((eq scheme 'dark)
         ,dark-body)
        (t
         (user-error "Unexpected colour scheme %s"
                     (symbol-name scheme))))))
#+end_src

* Theme
#+begin_src emacs-lisp
  (advice-add
   'load-theme
   :before
   (defun cnit-pre-load-theme (&rest _args)
     "Disable any loaded themes before enabling a new THEME.
  This prevents overlapping themes; something I would rarely want."
     (dolist (theme custom-enabled-themes)
       (disable-theme theme))))

  (defun cnit-load-system-theme ()
    "Load a theme based on the system color scheme."
    (require 'standard-themes)
    (when (fboundp 'cnit-with-system-colour-scheme)
      (cnit-with-system-colour-scheme
       (load-theme 'standard-dark-tinted t) (load-theme 'standard-light-tinted t))))

  (add-hook 'emacs-startup-hook #'cnit-load-system-theme)
#+end_src

* Productivity
Configuration for tools that enhance productivity, navigation, and
overall workflow in Emacs.

Navigate quickly around the visiable frames.
#+begin_src emacs-lisp
  (bind-key "M-j" #'avy-goto-char-timer)
  (bind-key "M-j" #'avy-isearch isearch-mode-map)
  (with-eval-after-load 'avy
    (setopt avy-style 'at-full
  	  avy-single-candidate-jump nil))
#+end_src

Embark for acting upon objects.
#+begin_src emacs-lisp
  (bind-key "C-." #'embark-act)

  (with-eval-after-load 'embark
    (keymap-set embark-general-map "g" #'gptel-add)
    (keymap-set embark-general-map "?" #'gptel-quick))
  (with-eval-after-load 'vertico-multiform
    (add-to-list
     'vertico-multiform-categories '(embark-keybinding grid)))

  (with-eval-after-load 'avy
    (setf (alist-get ?. avy-dispatch-alist)
          (defun avy-action-embark (pt)
            (unwind-protect
                (save-excursion
                  (goto-char pt)
                  (embark-act))
              (select-window (cdr (ring-ref avy-ring 0))))
            t)))
#+end_src

** Org mode
Most packages won't get there own section. However org mode and it's
various extensions are a significant part of the Emacs experience.

Apply automatic line breaking when inserting a space at a column.
#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (add-hook 'org-mode-hook #'auto-fill-mode))
#+end_src

Automatically tangle files on save, this helps with literate
code/configs to generate the resulting files.
#+begin_src emacs-lisp
  (defun cnit-org-after-save-babel-tangle ()
    "Automatically tangle org files when in 'org-mode'."
    (when (eq major-mode 'org-mode)
      (org-babel-tangle)))
  (with-eval-after-load 'org
    (add-hook 'after-save-hook #'cnit-org-after-save-babel-tangle))
#+end_src

Link the org src commands to help with automated code related
tasks that I want to be able to run prior to the save and exit.
#+begin_src emacs-lisp
  (with-eval-after-load 'org-src
    (defun cnit-org-edit-src-exit (orig &rest r)
      "Run before save hooks on save."
      ;;(run-hooks 'before-save-hook) ; BUG - Can't exit src code blocks without working formatter, impacts pressing return in src blocks.
      (apply orig r))
    (defun cnit-org-edit-src-save (orig &rest r)
      "Run before save hooks on save."
      (with-demoted-errors "Error running `before-save-hook': %S"
        (run-hooks 'before-save-hook))
      (apply orig r))
    (advice-add #'org-edit-src-save :around #'cnit-org-edit-src-save)
    (advice-add #'org-edit-src-exit :around #'cnit-org-edit-src-exit))
#+end_src

Org agenda basic settings. Configuration of location and files.
#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (setopt
     org-directory "~/nook/agenda"
     org-agenda-files '("inbox.org" "main.org")
     org-refile-targets '(("main.org" :maxlevel . 3)))
    (advice-add
     'org-refile
     :after (lambda (&rest _) (org-save-all-org-buffers))))
#+end_src

Org capture
#+begin_src emacs-lisp
  (keymap-set global-map "C-c c" #'org-capture)
  (with-eval-after-load 'org-capture
    (defun cnit-org-current-parent-target ()
      "Return a refile target pointing to the current heading."
      (org-back-to-heading t)
      ;; Return a cons of (heading . buffer)
      (let
          ((heading (nth 4 (org-heading-components))) ; get heading title
           (buf (current-buffer)))
        (list (list heading buf))))

    (setopt
     org-capture-templates
     '(("i"
        "Inbox"
        entry
        (file+headline "~/nook/agenda/inbox.org" "Inbox")
        "* TODO %? [/] [%]\n:PROPERTIES:\n:CREATED: %U\n:END:\n")
       ("s"
        "Subtask"
        entry
        (function cnit-org-current-parent-target)
        "* TODO %? [/][%]\n:PROPERTIES:\n:CREATED: %U\n:END:\n"))))
#+end_src

Org agenda views
#+begin_src emacs-lisp
  (bind-key "C-c o" #'org-agenda)
  (with-eval-after-load 'org-agenda
    (setopt org-agenda-custom-commands
            '(("r"
               "Review"
               tags-todo
               "+inbox"
               ((org-agenda-overriding-header "Inbox")))
              ("m" "Main tasks"
               ((todo
                 ""
                 ((org-agenda-files '("main.org"))
                  (org-agenda-overriding-header "Main Tasks"))))))))
#+end_src

Org babel for evaluating code blocks.
#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp .t) (eshell . t) (shell . t))))
#+end_src

* Editing
Tools and enhancements to make editing more efficient and
precise. Focuses on improving readability, providing structural
guidance, and automating routine tasks.

Highlight unmatched closing delimiters only in the error face
foreground colour. This will help with editing to highlight any
incorrectly closed blocks.
#+begin_src emacs-lisp
  (with-eval-after-load 'rainbow-delimiters
    (setopt rainbow-delimiters-max-face-count 1)
    (set-face-attribute 'rainbow-delimiters-unmatched-face nil
                        :foreground 'unspecified
                        :inherit 'error))
#+end_src

Ediff is used for easy working with buffer differences. By default it
uses a second frame for the control panel, but that doesn't work well
with tiling window managers.
#+begin_src emacs-lisp
  (with-eval-after-load 'ediff-wind
    (winner-mode t)
    (add-hook 'ediff-after-quit-hook-internal 'winner-undo)
    (setopt
     ediff-window-setup-function #'ediff-setup-windows-plain
     ediff-split-window-function #'split-window-sensibly))
#+end_src

Ansi color dwim. Will apply to region if select, otherwise whole
buffer. Run with prefix to preserve sequences rather than remove.
#+begin_src emacs-lisp
  (defun cnit-ansi-color-dwim (&optional arg)
    "Apply ansi-color to region if active, else to whole buffer.
  With prefix ARG, preserve color sequences (don't remove them)."
    (interactive "P")
    (let* ((beg
            (if (use-region-p)
                (region-beginning)
              (point-min)))
           (end
            (if (use-region-p)
                (region-end)
              (point-max))))
      (if arg
          (ansi-color-apply-on-region beg end)
        (ansi-color-apply-on-region beg end t))))

  (defvar buffer-quick-edits-prefix-map
    (let ((map (make-sparse-keymap)))
      (define-key map "c" 'cnit-ansi-color-dwim)
      map)
    "Keymap for buffer quick edits.")

  (bind-key "C-c b" buffer-quick-edits-prefix-map)
#+end_src

* Project
This section covers managing projects, whether version-controlled or
not. It provides tools for navigating, planning, and tracking work
across different contexts, from codebases to general tasks. The goal
is to keep all project-related activities organized and consistent.

Bindings for managing projects, these are typically git based projects
as I don't use other vc systems.
#+begin_src emacs-lisp
  (advice-add
   #'magit-project-status
   :before
   (defun cnit-magit-project-status ()
     (require 'project)))
  (keymap-set project-prefix-map "v" #'magit-project-status)
  (with-eval-after-load 'project
    (setopt
     project-switch-use-entire-map t
     project-mode-line nil))
#+end_src

Project memoization performance fix for the project modeline when the
file is not in a project. Refer to Emacs bug for the reason I have
this here
https://lists.gnu.org/archive/html/bug-gnu-emacs/2025-05/msg01039.html.
#+begin_src emacs-lisp
  (with-eval-after-load 'project
    (defun cnit-memoize-project-current
        (orig &optional prompt directory)
      (if (boundp 'memoize-project-current--cache)
          memoize-project-current--cache
        (set
         (make-local-variable 'memoize-project-current--cache)
         (funcall orig prompt directory))))
    (defun cnit-project-mode-line-format ()
      "Memoize 'project-current' for mode line performance."
      (let ((original-project-current
             (symbol-function 'project-current)))
        (unwind-protect
            (progn
              (fset 'project-current
                    (lambda (&optional prompt directory)
                      (cnit-memoize-project-current
                       original-project-current prompt directory)))
              (project-mode-line-format))
          (fset 'project-current original-project-current))))
    (advice-add
     'project-mode-line-format
     :override #'cnit-project-mode-line-format))
#+end_src

Basig magit settings.
#+begin_src emacs-lisp
  (with-eval-after-load 'magit
    (setopt
     magit-commit-show-diff nil
     magit-process-popup-time 5))
#+end_src
Magit worktree enhancements. Creation of worktree in standard folder
using branch naming scheme.
#+begin_src emacs-lisp
  (autoload 'cnit-magit-worktree-checkout-existing "magit-worktrees"
    nil
    t)
  (autoload 'cnit-magit-worktree-chekout-new "magit-worktrees" nil t)
  (with-eval-after-load 'magit
    (transient-append-suffix
     'magit-worktree "c"
     '("f" "from branch" cnit-magit-worktree-checkout-existing))
    (transient-append-suffix
     'magit-worktree "f"
     '("n" "new branch" cnit-magit-worktree-chekout-new)))
#+end_src

Cleanup any projects that are inside other projects. This is to help
cleanup modules that are downloaded as part of builds, tests and
pre-commits.
#+begin_src emacs-lisp
  (defun cnit/project-prune-nested-projects ()
    "Remove projects from `project--list` that are nested inside other projects.
  Keeps only the topmost project directories.

  This filters `project--list` in place and writes the updated list to disk."
    (interactive)
    (require 'seq)
    (project--ensure-read-project-list)
    (let* ((projects (mapcar #'car project--list))
           (sorted (seq-sort #'string-lessp projects))
           (pruned '())
           (last-root nil))
      ;; Go linearly through sorted list; skip any path that’s under the last kept root
      (dolist (proj sorted)
        (unless (and last-root
                     (string-prefix-p
                      (file-name-as-directory last-root)
                      (file-name-as-directory proj)
                      (file-name-case-insensitive-p proj)))
          (push proj pruned)
          (setq last-root proj)))

      ;; Keep only entries whose root is in pruned list
      (setq project--list
            (seq-filter
             (lambda (entry) (member (car entry) pruned))
             project--list))

      (project--write-project-list)
      (message "Pruned nested projects; %d remain"
               (length project--list))
      (length project--list)))
#+end_src

Allow safe directories list for dir-locals to prevent being asked
repeatedly.
#+begin_src emacs-lisp
  (defvar cnit-trusted-dir-locals
    '("~/nook/" "~/projects/work/" "~/projects/personal/")
    "List of directories whose .dir-locals.el files are fully trusted.")

  (defun cnit-trusted-dir-p (dir)
    "Return non-nil if DIR is in or under one of `cnit-trusted-dir-locals`."
    (let ((dir (expand-file-name dir)))
      (seq-some
       (lambda (trusted)
         (string-prefix-p (expand-file-name trusted) dir))
       cnit-trusted-dir-locals)))

  (defun cnit-hack-local
      (orig-fun all-vars unsafe-vars risky-vars dir-name)
    (if (cnit-trusted-dir-p dir-name)
        t ;; Automatically trust everything
      (apply orig-fun
             variables
             all-vars
             unsafe-vars
             risky-vars
             dir-name)))

  (advice-add 'hack-local-variables-confirm :around #'cnit-hack-local)
#+end_src

* Completions
This section will include all completion types and options. This
includes, but is not limited to, programming, textual, shell and LLM
completions.

Improve on the inbuilt completions. Display multiple candidates to
make selections easier.
#+begin_src emacs-lisp
  (with-eval-after-load 'vertico
    (setopt vertico-cycle t)
    (bind-key "C-<return>" #'vertico-exit-input 'vertico-map))
#+end_src

Improved filering of completion candidates. Helps to find things
easier using different methods such as out of order regexps.
#+begin_src emacs-lisp
    (setopt completion-styles '(orderless basic)
    	completion-category-overrides '((file (styles basic partial-completion))))
#+end_src

Change dabbrev to hippie expand for better completion capabilities.
#+begin_src emacs-lisp
  (global-set-key [remap dabbrev-expand] 'hippie-expand)
#+end_src

Completion in region enhancements. Show in popup by point and allow
for selection using standard movement keys.
#+begin_src emacs-lisp
  (autoload #'corfu--in-region "corfu")
  (setopt completion-in-region-function 'corfu--in-region)
  (with-eval-after-load 'corfu
    (setopt
     corfu-cycle t))
#+end_src

Template package configuration.
#+begin_src emacs-lisp
  (defun tempel-setup-capf ()
    "Add the Tempel Capf to `completion-at-point-functions'"
    (setq-local completion-at-point-functions
                (cons #'tempel-expand completion-at-point-functions)))

  (add-hook 'conf-mode-hook 'tempel-setup-capf)
  (add-hook 'prog-mode-hook 'tempel-setup-capf)
  (add-hook 'text-mode-hook 'tempel-setup-capf)

  (bind-key "C-c t" #'tempel-insert)
#+end_src

Minibuffer completions annotations. Applies useful extended details
such as documentation, values, file details etc.
#+begin_src emacs-lisp
  (with-eval-after-load 'marginalia
    (bind-key "M-a" #'marginalia-cycle 'minibuffer-mode-map))
#+end_src

Gptel
#+begin_src emacs-lisp
  (defvar gptel-prefix
    (let ((map (make-sparse-keymap)))
      (keymap-set map "b" #'gptel)
      (keymap-set map "f" #'gptel-add-file)
      (keymap-set map "m" #'gptel-menu)
      (keymap-set map "p" #'gptel-system-prompt)
      (keymap-set map "q" #'gptel-quick)
      (keymap-set map "r" #'gptel-add)
      (keymap-set map "s" #'gptel-send)
      (keymap-set map "t" #'gptel-tools)
      (keymap-set map "w" #'gptel-rewrite)
      map)
    "Keymap for GPTel related commands.")

  (keymap-set global-map "C-c g" gptel-prefix)
  (with-eval-after-load 'gptel
    (let ((map gptel-prefix))
      (keymap-set map "d" #'gptel-context-remove)
      (keymap-set map "D" #'gptel-context-remove-all))
    (setopt
     gptel-backend (gptel-make-gh-copilot "Copilot")
     gptel-model 'gpt-4.1
     gptel-default-mode 'org-mode)
    (add-hook 'gptel-mode-hook 'visual-line-mode)
    (add-hook 'gptel-post-stream-hook 'gptel-auto-scroll))
#+end_src

* Tools
This section covers general tools that don't fit into any other
area. This will cover things such as build, debug, shells and anything
else that is a general function or tool.

Capture ansi color codes in complilation buffer for better display.
#+begin_src emacs-lisp
  (with-eval-after-load 'compile
    (add-hook 'compilation-filter-hook 'ansi-color-compilation-filter))
#+end_src

Use emacs to help entering text into any program.
#+begin_src emacs-lisp
  (require 'emacs-everywhere)

  (setq
   emacs-everywhere-system-configs
   (append
    emacs-everywhere-system-configs
    '(((wayland . niri)
       :focus-command ("niri" "msg" "action" "focus-window" "--id" "%w")
       :info-function emacs-everywhere--app-info-linux-niri))))

  (defun emacs-everywhere--app-info-linux-niri ()
    "Return information on the current active window, on a Linux Niri session."
    (require 'json)
    (let* ((json
            (json-read-from-string
             (emacs-everywhere--call
              "niri" "msg" "-j" "focused-window"))) ;; -j for json
           (wid (cdr (assq 'id json)))
           (window-id
            (if (numberp wid)
                (number-to-string wid)
              wid))
           (window-title (cdr (assq 'title json)))
           (app-name (cdr (assq 'app_id json)))
           (window-geometry nil)) ;; no geometry in niri
      (make-emacs-everywhere-app
       :id window-id
       :class app-name
       :title window-title
       :geometry window-geometry)))
#+end_src

Kubenetes cluster management.
#+begin_src emacs-lisp
  (autoload 'kele-dispatch "kele" nil t)
  (bind-key "C-c k" #'kele-dispatch)
  (with-eval-after-load 'kele
    (kele-mode)
    (defun kele--list-kinds (context namespace &rest kinds)
      (magit-insert-section
       (kele-list-root)
       (magit-insert-section
        (overview) (magit-insert-heading "Overview")
        (insert
         (propertize "Context: " 'font-lock-face 'header-line)
         context
         "\n")
        (when namespace
          (insert
           (propertize "Namespace: "
                       'font-lock-face
                       'header-line)
           namespace "\n"))
        (insert
         (propertize "Last Updated: " 'font-lock-face 'header-line)
         (format-time-string "%Y-%m-%d %H:%M:%S"
                             kele--list-snapshot-time)
         "\n")
        (insert "\n"))
       (dolist (kind kinds)
         (-let*
          ((gv
            (car
             (kele--get-groupversions-for-type
              kele--global-discovery-cache
              kind
              :context context)))
           ((group version) (kele--groupversion-split gv))
           (gvk
            (kele--gvk-create
             :group group
             :version version
             :kind kind)))
          (condition-case err
              (magit-insert-section
               (kele-list-table `((gvk . ,gvk)))
               (magit-insert-heading
                (format
                 "%s: %s"
                 (propertize "Resources"
                             'font-lock-face 'magit-section-heading)
                 (propertize kind
                             'font-lock-face 'kele-resource-kind-face)))
               (magit-insert-section-body
                (vtable-insert
                 (kele--vtable-tabulate gvk context namespace))
                (vtable-end-of-table) (insert "\n")))
            (error
             (message "[kele] Failed to list %s: %s"
                      kind
                      (error-message-string err))))))))
    (defun kele--edit-resource ()
      (interactive nil kele-get-mode)
      (-let*
       ((ctx kele--current-resource-buffer-context)
        ((&alist
          'kind
          kind
          'apiVersion
          api-version
          'metadata
          (&alist 'name name 'namespace namespace))
         (kele--resource-buffer-context-resource ctx))
        (context (kele--resource-buffer-context-context ctx)))
       (with-editor
        (kele-kubectl-do
         "edit"
         "--context"
         context
         "--namespace"
         namespace
         kind
         name))))
    (bind-key "e" #'kele--edit-resource kele-get-mode-map))
#+end_src

* Window manager support
This section defines functions and settings to support using emacs
functionality directly from the window manager through the use of
emacsclient.

Allow capturing org inbox tasks.
#+begin_src emacs-lisp
  ;; emacsclient -s wm -e '(cnit-wm-org-capture)'

  (advice-add
   'org-capture-finalize
   :after
   (defun cnit-wm-org-capture-delete-frame (&rest _unused)
     (if (equal "Org Capture" (frame-parameter nil 'name))
         (delete-frame))))

  (defun cnit-wm-org-capture ()
    (interactive)
    (require 'cl-lib)
    (let ((frame
           (make-frame
            '((name . "Org Capture")
              (window-system . pgtk)
              ;; (minibuffer . nil)
              (undecorated . t)
              (vertical-scroll-bars . nil)
              (horizontal-scroll-bars . nil)
              (menu-bar-lines . 0)
              (tool-bar-lines . 0)))))
      (with-selected-frame frame
        (cl-letf (((symbol-function 'switch-to-buffer-other-window)
                   'switch-to-buffer))
          (org-capture nil "i")
          (setq-local mode-line-format nil)
          (delete-other-windows)))))
#+end_src

* Major modes
Options and configuration of major modes. A large proportion of major
modes will be programming languages themselves, however this section
also covers non-programming major modes.

** Dired mode
#+begin_src emacs-lisp
  (with-eval-after-load 'dired
    (add-hook 'dired-mode-hook (lambda () (dired-omit-mode 1)))
    (setopt
     dired-kill-when-opening-new-dired-buffer t
     dired-do-revert-buffer t
     dired-auto-revert-buffer t
     dired-dwim-target t))

  (with-eval-after-load 'wdired
    (setopt wdired-allow-to-change-permissions t))
#+end_src

** Prog mode
Enable supportive modes for programming.
#+begin_src emacs-lisp
  (add-hook
   'prog-mode-hook
   (lambda ()
     (rainbow-delimiters-mode t)))
#+end_src

** Emacs Lisp
Indentation configuration
#+begin_src emacs-lisp
  (with-eval-after-load 'emacs-mode
    (add-hook
     'emacs-lisp-mode
     (Lambda
      ()
      (setopt
       indent-tabs-mode nil
       lisp-indent-function nil
       lisp-indent-offset 2))))
#+end_src

Check for balanced parameters prior to allowing save.
#+begin_src emacs-lisp
  (add-hook 'before-save-hook
            (lambda ()
              (when (derived-mode-p 'lisp-data-mode)
                (check-parens)))
            -90)
#+end_src

Templates
#+begin_src lisp-data :tangle templates
  org-mode

  (src "#+begin_src " q n r n "#+end_src")
  (elisp "#+begin_src emacs-lisp" n r n "#+end_src" :post (org-edit-src-code))
#+end_src

** Shell


** YAML

Indentation is a pain, but [[https://github.com/nverno/yaml-indent/blob/master/yaml-indent.el][here's]] a possible improvement reference

** Nix
#+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist `(,(rx ".nix" string-end) . nix-ts-mode))
#+end_src

* footers
#+begin_src emacs-lisp :comments no :tangle early-init.el
  (provide 'early-init)

  ;;; early-init.el ends here
#+end_src

#+begin_src emacs-lisp :comments no
  (provide 'init)

  ;;; init.el ends here
#+end_src

#+begin_src emacs-lisp :comments no :tangle cnit-functions.el
  (provide 'init)

  ;;; cnit-functions.el ends here
#+end_src
