{ config, wolfLib, ... }:
{
  xdg.configFile."theme-output".text =
    let
      colors = config.wolf.theme.colors;
      colorBases = [
        "red"
        "orange"
        "yellow"
        "lime"
        "green"
        "springGreen"
        "cyan"
        "azure"
        "blue"
        "violet"
        "magenta"
        "rose"
        "gray"
        "brown"
      ];

      colorNames =
        [
          "background"
          "foreground"
          "light"
          "dark"
          "weak"
          "strong"
        ]
        ++ (builtins.concatLists (
          map (base: [
            base
            "weak${wolfLib.capitalize base}"
            "strong${wolfLib.capitalize base}"
            "light${wolfLib.capitalize base}"
            "dark${wolfLib.capitalize base}"
            "background${wolfLib.capitalize base}"
          ]) colorBases
        ));

      colorLines = builtins.concatStringsSep "\n" (
        builtins.map (name: "${name} = \"${colors.${name}}\"") colorNames
      );
    in
    ''
      # This file is generated by the theme-output module.
      # It contains the current theme settings for the user.
      # Do not edit this file manually.

      [theme]
      name = "Default Theme"
      ${colorLines}
    '';
}
